# Generated by Django 4.1.5 on 2023-03-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mylife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=12)),
                ('topic', models.CharField(max_length=12)),
                ('college', models.CharField(max_length=12)),
                ('school', models.CharField(max_length=12)),
                ('rollno', models.CharField(max_length=12)),
            ],
        ),
    ]
