# Generated by Django 4.1.5 on 2023-03-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylife',
            name='age',
            field=models.CharField(max_length=112),
        ),
        migrations.AlterField(
            model_name='mylife',
            name='college',
            field=models.CharField(max_length=112),
        ),
        migrations.AlterField(
            model_name='mylife',
            name='rollno',
            field=models.CharField(max_length=112),
        ),
        migrations.AlterField(
            model_name='mylife',
            name='school',
            field=models.CharField(max_length=112),
        ),
        migrations.AlterField(
            model_name='mylife',
            name='topic',
            field=models.CharField(max_length=112),
        ),
    ]
